import Head from "next/head"

const HeadDoc = ({ title = "Pokemon App" }) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default HeadDoc
